import requests
import pprint
import json
import time

url = "https://api.sse.cisco.com/policies/v2/destinationlists"

#Make sure to use the correct Bearer Token
BT = "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcyNmI5MGUzLWQ1MjYtNGMzZS1iN2QzLTllYjA5NWU2ZWRlOSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bWJyZWxsYS1hdXRoei9hdXRoc3ZjIiwic3ViIjoib3JnLzgyMTgwODQvY2xpZW50LzJlMDBjMzQ3ZTA5NjQzMWI4MWFiN2JlNjNjMTYxZDk2IiwiZXhwIjoxNzA4NjMzMTg2LCJuYmYiOjE3MDg2Mjk1ODYsImlhdCI6MTcwODYyOTU4Niwic2NvcGUiOiJkZXBsb3ltZW50cy5uZXR3b3Jrczp3cml0ZSBkZXBsb3ltZW50cy5uZXR3b3JrczpyZWFkIGRlcGxveW1lbnRzLnJvYW1pbmdjb21wdXRlcnM6d3JpdGUgZGVwbG95bWVudHMucm9hbWluZ2NvbXB1dGVyczpyZWFkIGRlcGxveW1lbnRzLmludGVybmFsbmV0d29ya3M6d3JpdGUgZGVwbG95bWVudHMuaW50ZXJuYWxuZXR3b3JrczpyZWFkIGRlcGxveW1lbnRzLmludGVybmFsZG9tYWluczp3cml0ZSBkZXBsb3ltZW50cy5pbnRlcm5hbGRvbWFpbnM6cmVhZCBkZXBsb3ltZW50cy52aXJ0dWFsYXBwbGlhbmNlczp3cml0ZSBkZXBsb3ltZW50cy52aXJ0dWFsYXBwbGlhbmNlczpyZWFkIGRlcGxveW1lbnRzLnNpdGVzOndyaXRlIGRlcGxveW1lbnRzLnNpdGVzOnJlYWQgZGVwbG95bWVudHMuZGF0YWNlbnRlcnM6cmVhZCBkZXBsb3ltZW50cy50dW5uZWxzOndyaXRlIGRlcGxveW1lbnRzLnR1bm5lbHM6cmVhZCBkZXBsb3ltZW50cy5uZXR3b3JrZGV2aWNlczp3cml0ZSBkZXBsb3ltZW50cy5uZXR3b3JrZGV2aWNlczpyZWFkIGRlcGxveW1lbnRzLnBvbGljaWVzOndyaXRlIGRlcGxveW1lbnRzLnBvbGljaWVzOnJlYWQgZGVwbG95bWVudHMucmVnaXN0ZXJlZGFwcGxpYW5jZXM6d3JpdGUgZGVwbG95bWVudHMucmVnaXN0ZXJlZGFwcGxpYW5jZXM6cmVhZCBkZXBsb3ltZW50cy5uZXR3b3JrdHVubmVsZ3JvdXBzOndyaXRlIGRlcGxveW1lbnRzLm5ldHdvcmt0dW5uZWxncm91cHM6cmVhZCBkZXBsb3ltZW50cy5yZWdpb25zOnJlYWQgZGVwbG95bWVudHMuY29ubmVjdG9yYWdlbnQ6d3JpdGUgZGVwbG95bWVudHMudGFnZGV2aWNlczp3cml0ZSBkZXBsb3ltZW50cy50YWdkZXZpY2VzOnJlYWQgZGVwbG95bWVudHMudGFnczp3cml0ZSBkZXBsb3ltZW50cy50YWdzOnJlYWQgcG9saWNpZXMuZGVzdGluYXRpb25saXN0czp3cml0ZSBwb2xpY2llcy5kZXN0aW5hdGlvbmxpc3RzOnJlYWQgcG9saWNpZXMuZGVzdGluYXRpb25zOndyaXRlIHBvbGljaWVzLmRlc3RpbmF0aW9uczpyZWFkIHBvbGljaWVzLmRscGluZGV4ZXI6d3JpdGUgcG9saWNpZXMuZGxwaW5kZXhlcjpyZWFkIHBvbGljaWVzLnJ1bGVzOndyaXRlIHBvbGljaWVzLnJ1bGVzOnJlYWQgcmVwb3J0cy5ncmFudWxhcmV2ZW50czpyZWFkIHJlcG9ydHMudXRpbGl0aWVzOnJlYWQgcmVwb3J0cy5hZ2dyZWdhdGlvbnM6d3JpdGUgcmVwb3J0cy5hZ2dyZWdhdGlvbnM6cmVhZCByZXBvcnRzLmN1c3RvbWVyczp3cml0ZSByZXBvcnRzLmN1c3RvbWVyczpyZWFkIHJlcG9ydHMuYXBwZGlzY292ZXJ5OndyaXRlIHJlcG9ydHMuYXBwZGlzY292ZXJ5OnJlYWQgcmVwb3J0cy5hcGl1c2FnZTpyZWFkIHJlcG9ydHMudXNhZ2UuaW5nZXN0OndyaXRlIHJlcG9ydHMudXNhZ2UubWV0cmljczpyZWFkIHJlcG9ydHMudXNhZ2Uuc3RhdHVzOnJlYWQgcmVwb3J0cy5wcml2YXRlcmVzb3VyY2VzOnJlYWQgcmVwb3J0cy5zdW1tYXJpZXNieXJ1bGU6cmVhZCBhdXRoLnN3YTpyZWFkIGFkbWluLnVzZXJzOndyaXRlIGFkbWluLnVzZXJzOnJlYWQgYWRtaW4ucm9sZXM6cmVhZCBhZG1pbi5vcmdhbml6YXRpb25zOndyaXRlIGFkbWluLm9yZ2FuaXphdGlvbnM6cmVhZCBhZG1pbi5wYXNzd29yZHJlc2V0OndyaXRlIGludmVzdGlnYXRlLmludmVzdGlnYXRlOnJlYWQgaW52ZXN0aWdhdGUuYnVsazpyZWFkIiwiYXV0aHpfZG9uZSI6ZmFsc2V9.LkejI3d-NlKym1g2-b4VX7g3bNVXbf-Q5ncROHSwnanu1cJWvfJhYzfkwKtihIqkYhJaEmYB-hGZCWoZ_nm0e5LGYZrZcPyUuSQBX07vPsrCZ5zkdZswjWyIk8hUs2YVLtlIBYBHm9Ca3LoaTDdWZFESmpQdxxbGm3VgCMeeoAdW3LPIBb-hdLkIXh_zJbmAf82zg8QDBPywaWYQf9uSECzdG1MrTHgq4mcACZKwDUQGWn1z7u3RqUI9GxZFyVJFch9V_GTLa3pUBlyx-A6fDEZPQaS_sfTdDPZw59WyrAZM_HwTDgmr0cDD-4O1YEvk57VPhpq_1-GLNCBvyooEpQ"

headers = { 'Authorization':BT
,"Accept": "application/json" }

response = requests.request('GET', url, headers=headers)

json_object = json.loads(response.content)

#pprint.pprint(json_object)
x=1
for item in json_object["data"]:
	print(f"Destination List -- {x}")
	pprint.pprint(item['name'])
	pprint.pprint(item["id"])
	pprint.pprint(item["meta"]["destinationCount"])
	print("\n")
	x+=1

choice = input("DestinationList ID: ")

url2 = "https://api.sse.cisco.com/policies/v2/destinationlists/" + choice + "/destinations"
response = requests.request('GET', url2, headers=headers)
json_dest = json.loads(response.content)
pprint.pprint(json_dest)
time.sleep(50)



